# Generated by Django 3.2.4 on 2021-06-29 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0007_carouselimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShaftSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.CharField(max_length=40)),
                ('diameter', models.CharField(max_length=40)),
                ('ferrule', models.CharField(max_length=40)),
                ('length', models.CharField(max_length=40)),
                ('joint', models.CharField(max_length=40)),
                ('taper', models.CharField(max_length=40)),
            ],
        ),
    ]
