# Generated by Django 3.2.4 on 2021-06-29 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0008_shaftspecs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShaftSpecs',
            new_name='ShaftSpec',
        ),
    ]
